######################## default configuration ####################
baseURL = "https://thelaluka.github.io/CabinetOsteopathieDutertre/"
languageCode = "en-us"
title = "Osteopathie du sport | Aurélie Dutertre"
theme = "hargo-hugo-ecommerce-theme"
summaryLength = "20"
paginate = 10
disqusShortname = ""
publishDir = "docs"

[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"


############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "L'Ostéopathie"
  URL = "osteopathie-docu"  
  weight = 1

  [[menu.main]]
  name = "Tarifs"
  URL = "osteopathie-tarifs"  
  weight = 2

  [[menu.main]]
  name = "La SmartBoard"
  URL = "smartboard"  
  weight = 3

  [[menu.main]]
  name = "Liens utiles"
  URL = "liens-utiles" 
  weight = 4

  [[menu.main]]
  name = "Contact"
  URL = "contact" 
  weight = 5

  ############# footer menu #############
  [[menu.footer]]
  name = "Accueil"
  URL = "/"
  weight = 1

  [[menu.footer]]
  name = "L'Ostéopathie, c'est quoi ?"
  URL = "osteopathie-docu"
  weight = 2

  [[menu.footer]]
  name = "Ostéopathie-tarifs"
  URL = "osteopathie-tarifs"
  weight = 3

  [[menu.footer]]
  name = "Liens Utiles"
  URL = "liens-utiles"
  weight = 4

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 5



#################### default parameters ################################
[params]
logo = "images/logo.png"
logojpg = "images/logo.jpg"
home = "Accueil"
# Meta data
description = "Bienvenue au cabinet d'ostéopathie d'Aurélie Dutertre, situé à Grenoble, quartier Vigny Musset"
author = "Themefisher"
# google map
# gmapAPI = "nope, me no like useless expenses :)"
# mapLatitude = "45.16739614361891"
# mapLongitude = "5.72391508737948"
# mapMarker = "images/marker.png"
# Google Analitycs
# googleAnalitycsID = "" # Your ID
# Contact Information
mobile = "06 27 37 49 38"
email = "aurelie.dutertre@yahoo.fr"
location = "46 rue Alfred de Vigny, 38100 Grenoble"
# copyright
copyright = "&copy; 2020-2021 · [GoHugo](https://gohugo.io/) · [HargoTheme](https://github.com/themefisher/hargo-hugo-ecommerce-theme) · ❤️ · [ThinkLoveShare](https://thinkloveshare.com/)"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  # [params.rating]
  # enable = true
  # websiteID = "444334"
  # publicKey = "811cf0927332bf51f2e12f84608594ac"

  # Social Site
  [[params.social]]
    icon = "fa-instagram"
    link = "https://www.instagram.com/aurelie.dutertre/"

  [[params.social]]
    icon = "fa-whatsapp"
    link = "https://wa.me/qr/DQO2MFZ6HGSTI1"

  [[params.social]]
    icon = "fa-facebook"
    link = "https://www.facebook.com/Aur%C3%A9lie-Dutertre-770845799602414/"

  [[params.social]]
    icon = "fa-linkedin"
    link = "https://www.linkedin.com/in/aurelie-dutertre-10435128/"
